# Model Configuration
model:
  name: "CNN"
  num_classes: 7
  dropout: 0.25
  lstm_hidden: 128

# Data Configuration
data:
  train_dir_izzy: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/train"
  test_dir_izzy: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/test"
  train_dir_emily: "/Users/shuang/Desktop/0_Emily/3_Fall25/ML/Project 2/data/train"
  test_dir_emily: "/Users/shuang/Desktop/0_Emily/3_Fall25/ML/Project 2/data/test"
  batch_size: 100
  image_size: [48, 48]

# Training Configuration
training:
  epochs: 14
  learning_rate: 0.0001
  optimizer: "Lion" # not connected to code, purely descriptive
  weight_decay: .1

# Hardware
device: "mps"
seed: 42

