# Model Configuration
model:
  name: "CNN"
  num_classes: 7
  dropout: 0.3

# Data Configuration
data:
  train_dir_izzy: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/train"
  test_dir_izzy: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/test"
  train_dir_emily: "/Users/shuang/Desktop/0_Emily/3_Fall25/ML/Project 2/data/train"
  test_dir_emily: "/Users/shuang/Desktop/0_Emily/3_Fall25/ML/Project 2/data/test"
  batch_size: 64
  image_size: [48, 48]

# Training Configuration
training:
  epochs: 15
  learning_rate: 0.001
  optimizer: "Adam" # not connected to code yet
  weight_decay: 0.0001

# Paths
paths:
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  results_dir: "results"

# Hardware
device: "mps"
seed: 42

# Logging
logging:
  log_interval: 10  # Log every 10 batches
  save_interval: 5  # Save checkpoint every 5 epochs
