# Model Configuration
model:
  name: "CNN"
  num_classes: 7
  dropout: 0.2

# Data Configuration
data:
  train_dir_izzy: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/train"
  test_dir_izzy: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/test"
  train_dir_emily: "/Users/shuang/Desktop/0_Emily/3_Fall25/ML/Project 2/data/train"
  test_dir_emily: "/Users/shuang/Desktop/0_Emily/3_Fall25/ML/Project 2/data/test"
  batch_size: 128
  image_size: [48, 48]

# Training Configuration
training:
  epochs: 6
  learning_rate: 0.0002
  optimizer: "Adam" # not connected to code yet
  weight_decay: .00015

# Hardware
device: "mps"
fallback_device: "cpu"
seed: 42

