# Model Configuration
model:
  name: "CNN"
  num_classes: 7
  pretrained: false
  dropout: 0.5

# Data Configuration
data:
  train_dir: "/Users/izzybedichek/Desktop/imp/grad_school/machine_learning/facial_recognition_CNN/data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  batch_size: 32
  num_workers: 0
  image_size: [48, 48]

# Training Configuration
training:
  epochs: 100
  learning_rate: 0.001
  optimizer: "Adam" # not connected to code yet
  weight_decay: 0.0001

# Paths
paths:
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  results_dir: "results"

# Hardware
device: "cpu"
seed: 42

# Logging
logging:
  log_interval: 10  # Log every 10 batches
  save_interval: 5  # Save checkpoint every 5 epochs
